name: Conventional Commits Checker
on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.0.3
