on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commits
        uses: crqra/conventional-commits-action@1.0.0
    
