name: Build Test
on:
  pull_request:
    branches:
      - main
    types: ['opened', 'reopened']
jobs:
  validate_pull_request:
    runs-on: windows-2019
    env:
      PathToSolution: src
      SolutionName: GitAnalyzer.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Nuget restore
        run: nuget restore ${{env.PathToSolution}}/${{env.SolutionName}}

      - name: Build
        run: msbuild ${{env.PathToSolution}}/${{env.SolutionName}} -t:rebuild -property:Configuration=Release
        
