name: Pull request compiler
on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    runs-on: windows-2019  
    env:
      PathToSolution: src
      SolutionName: GitAnalyzer.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Nuget
      uses: nuget/setup-nuget@v1

    - name: Nuget restore
      run: nuget restore ${{env.PathToSolution}}/${{env.SolutionName}}

    - name: Build app for release
      run: msbuild ${{env.PathToSolution}}/${{env.SolutionName}} -t:rebuild -property:Configuration=Release
