name: Create tag for release
on: 
  push:
    branches: 'main'
    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-2019  
    env:
      ReleaseVersion: not-set
      PathToPlugins: src/Plugins
      PathToVersionFile: src/GitAnalyzer/Properties/AssemblyInfo.cs
      PathToSolution: src
      SolutionName: GitAnalyzer.sln
      PathToBinaries: src/GitAnalyzer/bin/Release
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read build version
      id: read_build
      uses: juliangruber/read-file-action@v1.1.6
      with:
        path: ${{env.PathToVersionFile}}
        
    - name: Refine version string
      id: regex_match 
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: 'AssemblyFileVersion\(\".*\"'
        regex_flags: 'gim'
        search_string: ${{ steps.read_build.outputs.content }}
        
    - name: Refine version string 2
      id: regex_match2 
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(\d[.]?)+'
        regex_flags: 'gim'
        search_string: ${{ steps.regex_match.outputs.first_match }}
        
    - name: Set Release Version
      uses: allenevans/set-env@v2.0.0
      with:
        ReleaseVersion: release-v${{ steps.regex_match2.outputs.first_match }}
        
    - name: Tag commit as release
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{env.ReleaseVersion}}
  
